name: linux64

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install build-essential mesa-common-dev libgl1-mesa-dev libxkbcommon-x11-dev libfontconfig1 fuse libxcb-cursor-dev -y

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.*
          modules: qtwebengine qtwebchannel qtpositioning qtserialport

      - name: Build kleiner-brauhelfer-2
        run: |
          chmod +x ./build_linux64.sh
          chmod +x ./deployment/linux/64bit/deploy.sh
          chmod +x ./deployment/linux/64bit/AppImage/linuxdeploy-x86_64.AppImage
          chmod +x ./deployment/linux/64bit/AppImage/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x ./deployment/linux/64bit/AppImage/linuxdeploy-plugin-appimage-x86_64.AppImage
          chmod +x ./deployment/linux/64bit/AppImage/AppRun
          ./build_linux64.sh "${QT_ROOT_DIR}/bin/"
          mkdir -p deploy
          cp ./build-linux64/bin/kleiner-brauhelfer-2 deploy
          cp ./build-linux64/bin/kbh2_v2.x.x_linux_x64.deb deploy
          cp ./build-linux64/bin/kleiner-brauhelfer-2-x86_64.AppImage deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kleiner-brauhelfer-2
          path: deploy
