name: macOS

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          setup-python: 'true'
          version: 6.5.*
          modules: qtwebengine qtwebchannel qtpositioning

      - name: Build kleiner-brauhelfer-2
        run: |
          chmod +x ./build_macos.sh
          ./build_macos.sh "${QT_ROOT_DIR}/bin/" "-${{ github.sha }}"
          mkdir deploy
          cp build-macos/bin/kbh2_*.zip deploy/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kleiner-brauhelfer-2
          path: deploy
