name: win64

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.*
          modules: qtwebengine qtwebchannel qtpositioning

      - name: Build kleiner-brauhelfer-2
        shell: cmd
        run: |
          for /f "usebackq delims=#" %%a in (`"%PROGRAMFILES(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -property installationPath`) do set VSPATH=%%a
          call "%VSPATH%\VC\Auxiliary\Build\vcvars64.bat"
          mkdir build
          mkdir deploy
          cd build
          "%Qt6_Dir%\bin\qmake.exe" "..\kleiner-brauhelfer-2.pro" -config release
          nmake
          cd bin
          copy "kleiner-brauhelfer-2.exe" "../../deploy"
          cd ../..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kleiner-brauhelfer-2
          path: deploy
